#!/bin/sh
#
# rrdcollect-remote    init script file to start the rrdcollect-remote daemon.

test -f /usr/bin/rrdcollect-remote || exit 0

CONF=/etc/rrdcollect-remote/rrdcollect-remote.conf
SSH_KEY=/etc/rrdcollect-remote/rrdcollect-remote_sshkey

. /etc/default/rrdcollect-remote

if [ "$START" = "0" ]
then
    echo "RRD Collect Remote is disabled, check the /etc/default/rrdcollect-remote file for more info."
    exit
fi

if [ -f "$CONF.m4" ]
then
    CONF="$CONF.m4"
fi

ARGS="-c $CONF"

function init_sshkey()
{
    if test -f $CONF && grep -q "rsh-args.*-i.*$SSH_KEY" $CONF
    then
        if [ ! -f $SSH_KEY ]
        then
            echo
            echo -n "Init SSH keys with empty passphrase..."
            # create an ssh key with empty passphrase
            yes|ssh-keygen -q -f $SSH_KEY -t dsa -N ""
        fi
    fi
}

case "$1"
in
    start)
        echo -n "Starting RRD Collect Remote: rrdcollect-remote"
        init_sshkey
        start-stop-daemon --start --quiet --exec /usr/bin/rrdcollect-remote -- $ARGS
        echo "."
        ;;

    stop)
        echo -n "Stopping RRD Collect Remote: rrdcollect-remote"
        start-stop-daemon --stop --quiet --retry "INT/5/INT/10/INT/30/KILL/5" --pidfile /var/run/rrdcollect-remote.pid
        echo "."
        ;;

    reload|force-reload)
        echo -n "Reloading RRD Collect Remote: rrdcollect-remote"
        start-stop-daemon --stop --signal 1 --quiet --pidfile /var/run/rrdcollect-remote.pid
        echo "."
        ;;

    restart)
        echo -n "Stopping RRD Collect Remote: rrdcollect-remote"
        start-stop-daemon --stop --quiet --retry "INT/5/INT/10/INT/30/KILL/5" --pidfile /var/run/rrdcollect-remote.pid
        echo "."
        sleep 1
        echo -n "Starting RRD Collect Remote: rrdcollect-remote"
        init_sshkey
        start-stop-daemon --start --quiet --exec /usr/bin/rrdcollect-remote -- $ARGS
        echo "."
        ;;
    
    *)
        echo "Usage: /etc/init.d/rrdcollect-remote {start|stop|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
