#!/bin/sh
#
# statgrabber    init script file to start the statgrabber daemon.

test -f /usr/bin/statgrabber || exit 0

CONF=/etc/statgrabber/statgrabber.conf
SSH_KEY=/etc/statgrabber/statgrabber_sshkey
ARGS="-c $CONF"

function init_sshkey()
{
    if grep -q "rsh-args.*-i.*$SSH_KEY" $CONF
    then
        if [ ! -f $SSH_KEY ]
        then
            echo
            echo -n "Init SSH keys with empty passphrase..."
            # create an ssh key with empty passphrase
            yes|ssh-keygen -q -f $SSH_KEY -t dsa -N ""
        fi
    fi
}

case "$1"
in
    start)
        echo -n "Starting VDS filer agent: statgrabber"
        init_sshkey
        start-stop-daemon --start --quiet --exec /usr/bin/statgrabber -- $ARGS
        echo "."
        ;;

    stop)
        echo -n "Stopping VDS filer agent: statgrabber"
        start-stop-daemon --stop --quiet --retry "INT/5/INT/10/INT/30/KILL/5" --pidfile /var/run/statgrabber.pid
        echo "."
        ;;

    reload|force-reload)
        echo -n "Reloading VDS filer agent: statgrabber"
        start-stop-daemon --stop --signal 1 --quiet --pidfile /var/run/statgrabber.pid
        echo "."
        ;;

    restart)
        echo -n "Stopping VDS filer agent: statgrabber"
        start-stop-daemon --stop --quiet --retry "INT/5/INT/10/INT/30/KILL/5" --pidfile /var/run/statgrabber.pid
        echo "."
        sleep 1
        echo -n "Starting VDS filer agent: statgrabber"
        init_sshkey
        start-stop-daemon --start --quiet --exec /usr/bin/statgrabber -- $ARGS
        echo "."
        ;;
    
    *)
        echo "Usage: /etc/init.d/statgrabber {start|stop|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
